# Generated by Django 3.1.2 on 2021-01-11 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_type', models.CharField(choices=[('Bar Graph', 'Bar Graph'), ('Histogram', 'Histogram'), ('Line Graph', 'Line Graph'), ('Pie Chart', 'Pie Chart'), ('Scatter Plot', 'Scatter Plot'), ('Individual Statistic', 'Individual Statistic')], max_length=50)),
                ('selection', models.CharField(choices=[('Ethnicity', 'Ethnicity'), ('Career', 'Career'), ('Benefit Chapter', 'Benefit Chapter'), ('Usage by Date', 'Usage by Date'), ('College', 'College'), ('Total Usage by Location', 'Total Usage by Location')], max_length=50)),
                ('locations', models.CharField(max_length=50)),
                ('include_table', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('select_bar_color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Magenta', 'Magenta'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Black', 'Black')], max_length=50)),
                ('autoscale', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('max_count', models.IntegerField(max_length=50)),
                ('increment_by', models.IntegerField(max_length=50)),
                ('hist_data', models.CharField(max_length=50)),
                ('line_color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Magenta', 'Magenta'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Black', 'Black')], max_length=50)),
                ('data_units', models.CharField(choices=[('Percent of total', 'Percent of total'), ('Count', 'Count'), ('Both percentages and count', 'Both percentages and count')], max_length=50)),
                ('dot_color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Magenta', 'Magenta'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Black', 'Black')], max_length=50)),
                ('count_options', models.CharField(choices=[('Total Count', 'Total Count'), ('Daily average', 'Daily average'), ('Monthly average', 'Monthly average'), ('Yearly average', 'Yearly average')], max_length=50)),
                ('label_color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Magenta', 'Magenta'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Black', 'Black')], max_length=50)),
                ('statistic_font_color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Magenta', 'Magenta'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Black', 'Black')], max_length=50)),
                ('label_font_size', models.IntegerField(choices=[('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('24', '24'), ('28', '28'), ('32', '32'), ('36', '36'), ('42', '42'), ('48', '48'), ('72', '72')], max_length=50)),
                ('statistic_font_size', models.IntegerField(choices=[('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('24', '24'), ('28', '28'), ('32', '32'), ('36', '36'), ('42', '42'), ('48', '48'), ('72', '72')], max_length=50)),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
