# Generated by Django 3.1.2 on 2021-01-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpreferences',
            name='increment_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportpreferences',
            name='label_font_size',
            field=models.IntegerField(choices=[('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('24', '24'), ('28', '28'), ('32', '32'), ('36', '36'), ('42', '42'), ('48', '48'), ('72', '72')]),
        ),
        migrations.AlterField(
            model_name='reportpreferences',
            name='max_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reportpreferences',
            name='statistic_font_size',
            field=models.IntegerField(choices=[('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('24', '24'), ('28', '28'), ('32', '32'), ('36', '36'), ('42', '42'), ('48', '48'), ('72', '72')]),
        ),
    ]
