# Generated by Django 3.1.2 on 2021-01-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpresets',
            name='new_field',
        ),
    ]
