# Generated by Django 3.1.2 on 2021-02-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_auto_20210227_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpresets',
            old_name='label_color',
            new_name='header_font_color',
        ),
        migrations.RenameField(
            model_name='reportpresets',
            old_name='label_font_size',
            new_name='header_font_size',
        ),
    ]
