# Generated by Django 3.1.2 on 2021-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0003_auto_20210227_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpresets',
            name='multiple_bars',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
