# Generated by Django 3.1.2 on 2021-03-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0004_reportpresets_multiple_bars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpresets',
            name='select_all',
            field=models.BooleanField(null=True),
        ),
    ]
