# Generated by Django 3.1.2 on 2021-04-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0007_auto_20210418_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportpresets',
            old_name='custom_even_name',
            new_name='custom_event_name',
        ),
    ]
